### ISSUE TITLE
Please ignore all artifacts

### ISSUE THREAD

**Issue by chaosAD** [darklord1310/GDB-RSP-ARM-Cortex-M-Simulator#31]
Please ignore `.exe`, `.hex`, `.map`, `.elf`, and `.o` files. [Those](https://github.com/darklord1310/GDB-RSP-ARM-Cortex-M-Simulator/commit/b1ab4926ad4795c3e82664ae4d2986d00c1fa9c3) should not be in your repository.

**Comment by JacksonTeh** [comment]
Ignored all the file mention above.

**Comment by darklord1310** [comment]
Fixed
