### ISSUE TITLE
Table looks non-maintable and error prone

### ISSUE THREAD

**Issue by chaosAD** [darklord1310/GDB-RSP-ARM-Cortex-M-Simulator#43]
Can we find a way to not do [this](https://github.com/darklord1310/GDB-RSP-ARM-Cortex-M-Simulator/blob/master/src/ARMSimulator/Thumb32bitsTable.c#L235). This will invite error (I see duplicates) and not so maintainable.

How about define it in the global and use designated initializers, just like the following:

```
    int tb[] = {
    // 0b10xx00        LDR r0, xxx (T1 encoding)
      [0b100000] = 4,
      [0b100100] = 4,
      [0b101000] = 4,
      [0b101100] = 4,
    // 0b1000x0        STR r0, xxx (T12 encoding)
      [0b100000] = 5,
      [0b100010] = 5,
    };
```

Also the [table initializer code](https://github.com/darklord1310/GDB-RSP-ARM-Cortex-M-Simulator/blob/master/src/ARMSimulator/Thumb32bitsTable.c#L672)  looks very convoluted and waiting for trouble.

Are you sure [this](https://github.com/darklord1310/GDB-RSP-ARM-Cortex-M-Simulator/blob/master/src/ARMSimulator/Thumb32bitsTable.c#L832) and the following does not have `else` statements?

Anyway, you might want to re-look into this.

**Comment by darklord1310** [comment]
Fixed
