### ISSUE TITLE
480ba91bd commit fails some tests

### ISSUE THREAD

**Issue by chaosAD** [darklord1310/GDB-RSP-ARM-Cortex-M-Simulator#49]
This latest commit fails some [tests](https://github.com/darklord1310/GDB-RSP-ARM-Cortex-M-Simulator/commit/480ba91bd5822b548f6027e60fa126abaaf8b30b) on my machine. See the errors below:
## Test 'test_MemoryMapping.c'

Running test_MemoryMapping.exe...
## Test 'test_FloatingPointDataProcessing.c'

Running test_FloatingPointDataProcessing.exe...
## Test 'test_FileOperation.c'

Running test_FileOperation.exe...
## Test 'test_MyFlash.c'

Running test_MyFlash.exe...

---
## TEST OUTPUT

[test_MemoryMapping.c]
- ""

[test_FloatingPointDataProcessing.c]
- "1bf165f8"
- ""

[test_FileOperation.c]
- ""

[test_MyFlash.c]
- "error: cannot open the file C:/Users/Asus/Desktop/TDD/Project/GDB-RSP-ARM-Cortex-M-Simulator/TEST1.txt"
- "error: cannot open the file C:/Users/Asus/Desktop/TDD/Project/GDB-RSP-ARM-Cortex-M-Simulator/TEST1.txt"
- "error: cannot open the file C:/Users/Asus/Desktop/TDD/Project/GDB-RSP-ARM-Cortex-M-Simulator/TEST1.txt"
- "error: cannot open the file C:/Users/Asus/Desktop/TDD/Project/GDB-RSP-ARM-Cortex-M-Simulator/TEST1.txt"
- ""

---
## FAILED TEST SUMMARY

[test_MemoryMapping.c]
  Test: test_memoryMap_given_startAddress_and_a_function_should_map_the_function_according_to_the_start_address
  At line (49): "Expected 0x004033C4 Was 0x0041BA80"

  Test: test_memoryMap_given_startAddress_and_no_function_should_map_the_virtual_addr_to_the_physical_address
  At line (58): "Expected 0x0041CA80 Was 0x00000000"

[test_FloatingPointDataProcessing.c]
  Test: test_VMLAandVMLS_given_s1_0x2DE12E13_and_s2_0x2D893814_should_get_s0_0x1BF165F8
  At line (136): "Expected 468805112 Was 0"

[test_FileOperation.c]
  Test: test_backwardToForwardSlash_given_string_with_backslash_should_to_forward_slash
  At line (159): "Expected 'C:/Users/Asus/Desktop/TDD/Project/GDB-RSP-ARM-Cortex-M-Simulator' Was 'c:/Vennie/Projects/C/GDB-RSP-ARM-Cortex-M-Simulator'"

[test_MyFlash.c]
  Test: test_backwardToForwardSlash_given_string_with_backslash_should_to_forward_slash
  At line (79): "Expected 'C:/Users/Asus/Desktop/TDD/Project/GDB-RSP-ARM-Cortex-M-Simulator' Was 'c:/Vennie/Projects/C/GDB-RSP-ARM-Cortex-M-Simulator'"

---
## OVERALL TEST SUMMARY

TESTED:  17
PASSED:  12
FAILED:   5
IGNORED:  0

**Comment by darklord1310** [comment]
Solved
